In [2]:
import pandas as pd

In [3]:
# Series 
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series :\n",series)
print(type(series))

Series :
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
#Create a series from Dictionaries

data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
#Giving Different index based on our requirement
data = [10,20,30]
print(pd.Series(data))

index=['a','b','c']
pd.Series(data,index=index)

0    10
1    20
2    30
dtype: int64

a    10
b    20
c    30
dtype: int64

In [83]:
#DataFrame
# Creating a DataFrame from a dictionaries of list

data={
    'Name':['Shubham','Raunak','Rachit'],
    'Age':[30,35,20],
    'City':['Bangalore','Patna','Delhi']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Shubham   30  Bangalore
1   Raunak   35      Patna
2   Rachit   20      Delhi
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#
import numpy as np

np.array(df)

array([['Shubham', 30, 'Bangalore'],
       ['Raunak', 35, 'Patna'],
       ['Rachit', 20, 'Delhi']], dtype=object)

In [21]:
#Create a DataFrame from a list of Dictionaries

data=[
    {'name':'Shubham','age':30,'city':'Bangalore'},
    {'name':'Raunak','age':35,'city':'Patna'},
    {'name':'Rachit','age':20,'city':'Delhi'}
]

df=pd.DataFrame(data)
print(df)
print(type(df))

      name  age       city
0  Shubham   30  Bangalore
1   Raunak   35      Patna
2   Rachit   20      Delhi
<class 'pandas.core.frame.DataFrame'>

In [25]:
df1=pd.read_csv('sales.csv')

print(df1)

      Index      Customer Id First Name   Last Name                   Company  \
0         1  EB54EF1154C3A78    Heather    Callahan              Mosley-David
1         2  10dAcafEBbA5FcA   Kristina     Ferrell  Horn, Shepard and Watson
2         3  67DAB15Ebe4BE4a     Briana    Andersen               Irwin-Oneal
3         4  6d350C5E5eDB4EE      Patty       Ponce          Richardson Group
4         5  5820deAdCF23EFe   Kathleen   Mccormick              Carson-Burch
...     ...              ...        ...         ...                       ...
9995   9996  DD0caa06ebf217c     Meghan       Cline            Richardson LLC
9996   9997  C1C62ff90D0AfED   Jeremiah        Pena               Hodge-Nixon
9997   9998  2EfAa6Fe435A7DA      Peggy         Key                  Vang LLC
9998   9999  5dB06C3Fab5CCCb       Evan    Humphrey                 Gould Ltd
9999  10000  9903e8fF4D8Ff0F    Melissa  Montgomery              Burns-Holden

                  City                       Country                Phone 1  \
0     Lake Jeffborough                        Norway           043-797-5229
1           Aaronville                       Andorra           932-062-1802
2          East Jordan                         Nepal             8352752061
3     East Kristintown      Northern Mariana Islands           302.398.3833
4          Andresmouth                         Macao  001-184-153-9683x1497
...                ...                           ...                    ...
9995        Petersport                 Cote d'Ivoire   001-270-136-4738x419
9996        Briggsport                       Namibia   +1-531-494-7645x4844
9997    West Joyceport  United States Virgin Islands     520.109.2482x26052
9998    Camachochester                         Niger       001-465-242-9979
9999        Sparkstown                       Tunisia  +1-889-682-9490x65400

                    Phone 2                                 Email  \
0              915.112.1727          urangel@espinoza-francis.net
1        (209)172-7124x3651               xreese@hall-donovan.com
2             (567)135-1918         haleybraun@blevins-sexton.com
3          196-189-7767x770                  hohailey@anthony.com
4          552.051.2979x342      alvaradojesse@rangel-shields.com
...                     ...                                   ...
9995   001-349-692-1755x055             nicolasandrade@bates.info
9996  001-295-324-5502x5411                      tracy68@wade.com
9997  +1-602-934-5901x95106    mclaughlinjulia@barnett-dorsey.com
9998   001-639-955-2116x751  velazquezjessica@villegas-wilcox.com
9999     423.632.2539x98740               ngallagher@martinez.com

     Subscription Date                        Website
0           2020-08-26        http://www.escobar.org/
1           2020-04-27       https://tyler-pugh.info/
2           2022-03-22     https://www.mack-bell.net/
3           2020-07-02  https://delacruz-freeman.org/
4           2021-01-17            https://welch.info/
...                ...                            ...
9995        2022-04-27       http://thomas-ramos.com/
9996        2022-01-17      https://www.campbell.com/
9997        2022-01-13   http://www.george-scott.com/
9998        2020-04-14        https://www.payne.info/
9999        2020-06-27              http://nixon.net/

[10000 rows x 12 columns]

In [26]:
print(df1.head(5))

   Index      Customer Id First Name  Last Name                   Company  \
0      1  EB54EF1154C3A78    Heather   Callahan              Mosley-David
1      2  10dAcafEBbA5FcA   Kristina    Ferrell  Horn, Shepard and Watson
2      3  67DAB15Ebe4BE4a     Briana   Andersen               Irwin-Oneal
3      4  6d350C5E5eDB4EE      Patty      Ponce          Richardson Group
4      5  5820deAdCF23EFe   Kathleen  Mccormick              Carson-Burch

               City                   Country                Phone 1  \
0  Lake Jeffborough                    Norway           043-797-5229
1        Aaronville                   Andorra           932-062-1802
2       East Jordan                     Nepal             8352752061
3  East Kristintown  Northern Mariana Islands           302.398.3833
4       Andresmouth                     Macao  001-184-153-9683x1497

              Phone 2                             Email Subscription Date  \
0        915.112.1727      urangel@espinoza-francis.net        2020-08-26
1  (209)172-7124x3651           xreese@hall-donovan.com        2020-04-27
2       (567)135-1918     haleybraun@blevins-sexton.com        2022-03-22
3    196-189-7767x770              hohailey@anthony.com        2020-07-02
4    552.051.2979x342  alvaradojesse@rangel-shields.com        2021-01-17

                         Website
0        http://www.escobar.org/
1       https://tyler-pugh.info/
2     https://www.mack-bell.net/
3  https://delacruz-freeman.org/
4            https://welch.info/

In [27]:
print(df1.tail(5))

      Index      Customer Id First Name   Last Name         Company  \
9995   9996  DD0caa06ebf217c     Meghan       Cline  Richardson LLC
9996   9997  C1C62ff90D0AfED   Jeremiah        Pena     Hodge-Nixon
9997   9998  2EfAa6Fe435A7DA      Peggy         Key        Vang LLC
9998   9999  5dB06C3Fab5CCCb       Evan    Humphrey       Gould Ltd
9999  10000  9903e8fF4D8Ff0F    Melissa  Montgomery    Burns-Holden

                City                       Country                Phone 1  \
9995      Petersport                 Cote d'Ivoire   001-270-136-4738x419
9996      Briggsport                       Namibia   +1-531-494-7645x4844
9997  West Joyceport  United States Virgin Islands     520.109.2482x26052
9998  Camachochester                         Niger       001-465-242-9979
9999      Sparkstown                       Tunisia  +1-889-682-9490x65400

                    Phone 2                                 Email  \
9995   001-349-692-1755x055             nicolasandrade@bates.info
9996  001-295-324-5502x5411                      tracy68@wade.com
9997  +1-602-934-5901x95106    mclaughlinjulia@barnett-dorsey.com
9998   001-639-955-2116x751  velazquezjessica@villegas-wilcox.com
9999     423.632.2539x98740               ngallagher@martinez.com

     Subscription Date                       Website
9995        2022-04-27      http://thomas-ramos.com/
9996        2022-01-17     https://www.campbell.com/
9997        2022-01-13  http://www.george-scott.com/
9998        2020-04-14       https://www.payne.info/
9999        2020-06-27             http://nixon.net/

In [84]:
#Accessing Data from DataFrame

df

      Name  Age       City
0  Shubham   30  Bangalore
1   Raunak   35      Patna
2   Rachit   20      Delhi

In [85]:
df['Name']
type(df['Name'])

pandas.core.series.Series

In [86]:
df.loc[0]

Name      Shubham
Age            30
City    Bangalore
Name: 0, dtype: object

In [87]:
df.loc[df.Name=='Raunak']

     Name  Age   City
1  Raunak   35  Patna

In [88]:
df.iloc[1]

Name    Raunak
Age         35
City     Patna
Name: 1, dtype: object

In [89]:
df.iloc[[0,2]]

      Name  Age       City
0  Shubham   30  Bangalore
2   Rachit   20      Delhi

In [90]:
# Accessing a specified element

df

      Name  Age       City
0  Shubham   30  Bangalore
1   Raunak   35      Patna
2   Rachit   20      Delhi

In [91]:
df.at[0,'City']

'Bangalore'

In [92]:
df.at[2,'Age']

np.int64(20)

In [93]:
# Accessing a specified element using iat

df.iat[2,2]

'Delhi'

In [94]:
# Data Manipulation with DataFrames
df

      Name  Age       City
0  Shubham   30  Bangalore
1   Raunak   35      Patna
2   Rachit   20      Delhi

In [95]:
df['Salary']=[50000,35000,15000]
df

      Name  Age       City  Salary
0  Shubham   30  Bangalore   50000
1   Raunak   35      Patna   35000
2   Rachit   20      Delhi   15000

In [96]:
#Removing a column
df.drop('Salary',axis=1)

      Name  Age       City
0  Shubham   30  Bangalore
1   Raunak   35      Patna
2   Rachit   20      Delhi

In [97]:
df

      Name  Age       City  Salary
0  Shubham   30  Bangalore   50000
1   Raunak   35      Patna   35000
2   Rachit   20      Delhi   15000

In [98]:
df.drop('Salary',axis=1,inplace=True)

In [99]:
df

      Name  Age       City
0  Shubham   30  Bangalore
1   Raunak   35      Patna
2   Rachit   20      Delhi

In [100]:
#Operations on Dataframes

#Adding age to the column

df['Age']=df['Age']+1
df

      Name  Age       City
0  Shubham   31  Bangalore
1   Raunak   36      Patna
2   Rachit   21      Delhi

In [101]:
#Removing a row
df.drop(0)

     Name  Age   City
1  Raunak   36  Patna
2  Rachit   21  Delhi

In [102]:
df

      Name  Age       City
0  Shubham   31  Bangalore
1   Raunak   36      Patna
2   Rachit   21      Delhi

In [103]:
df.drop(0,inplace=True)

In [104]:
df

     Name  Age   City
1  Raunak   36  Patna
2  Rachit   21  Delhi

In [108]:
df1=pd.read_csv('sales.csv')
df1.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [109]:
#Display the data type of each column
print("Data Types: \n", df1.dtypes)

#Describe the DataFrame
print("Statistical Summary: \n", df.describe())

Data Types:
 Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object
Statistical Summary:
              Age
count   2.000000
mean   28.500000
std    10.606602
min    21.000000
25%    24.750000
50%    28.500000
75%    32.250000
max    36.000000

In [110]:
df1.describe

<bound method NDFrame.describe of       Index      Customer Id First Name   Last Name                   Company  \
0         1  EB54EF1154C3A78    Heather    Callahan              Mosley-David
1         2  10dAcafEBbA5FcA   Kristina     Ferrell  Horn, Shepard and Watson
2         3  67DAB15Ebe4BE4a     Briana    Andersen               Irwin-Oneal
3         4  6d350C5E5eDB4EE      Patty       Ponce          Richardson Group
4         5  5820deAdCF23EFe   Kathleen   Mccormick              Carson-Burch
...     ...              ...        ...         ...                       ...
9995   9996  DD0caa06ebf217c     Meghan       Cline            Richardson LLC
9996   9997  C1C62ff90D0AfED   Jeremiah        Pena               Hodge-Nixon
9997   9998  2EfAa6Fe435A7DA      Peggy         Key                  Vang LLC
9998   9999  5dB06C3Fab5CCCb       Evan    Humphrey                 Gould Ltd
9999  10000  9903e8fF4D8Ff0F    Melissa  Montgomery              Burns-Holden

                  City                       Country                Phone 1  \
0     Lake Jeffborough                        Norway           043-797-5229
1           Aaronville                       Andorra           932-062-1802
2          East Jordan                         Nepal             8352752061
3     East Kristintown      Northern Mariana Islands           302.398.3833
4          Andresmouth                         Macao  001-184-153-9683x1497
...                ...                           ...                    ...
9995        Petersport                 Cote d'Ivoire   001-270-136-4738x419
9996        Briggsport                       Namibia   +1-531-494-7645x4844
9997    West Joyceport  United States Virgin Islands     520.109.2482x26052
9998    Camachochester                         Niger       001-465-242-9979
9999        Sparkstown                       Tunisia  +1-889-682-9490x65400

                    Phone 2                                 Email  \
0              915.112.1727          urangel@espinoza-francis.net
1        (209)172-7124x3651               xreese@hall-donovan.com
2             (567)135-1918         haleybraun@blevins-sexton.com
3          196-189-7767x770                  hohailey@anthony.com
4          552.051.2979x342      alvaradojesse@rangel-shields.com
...                     ...                                   ...
9995   001-349-692-1755x055             nicolasandrade@bates.info
9996  001-295-324-5502x5411                      tracy68@wade.com
9997  +1-602-934-5901x95106    mclaughlinjulia@barnett-dorsey.com
9998   001-639-955-2116x751  velazquezjessica@villegas-wilcox.com
9999     423.632.2539x98740               ngallagher@martinez.com

     Subscription Date                        Website
0           2020-08-26        http://www.escobar.org/
1           2020-04-27       https://tyler-pugh.info/
2           2022-03-22     https://www.mack-bell.net/
3           2020-07-02  https://delacruz-freeman.org/
4           2021-01-17            https://welch.info/
...                ...                            ...
9995        2022-04-27       http://thomas-ramos.com/
9996        2022-01-17      https://www.campbell.com/
9997        2022-01-13   http://www.george-scott.com/
9998        2020-04-14        https://www.payne.info/
9999        2020-06-27              http://nixon.net/

[10000 rows x 12 columns]>